//Free to use and distribute
#include <iostream>
#include <string>
#include "vigenere.h"

// KEY1: STRINGLENGTHOFTHIRTYCHARACTERS
// KEY2: CRYPTOGRAPHYISWHATWEARESTUDYING
// KEY3: PRAISEBETOTHELORDFORHEHASHEARDMYCRYFORMERCY
// KEY4: ONEOFTHEBESTTELEVISIONSHOWSISPEAKYBLINDERSNODOUBT SUBSTITUTION

// KEY: HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HELLO HEL
// PLA: HELPM EDEAR BRYAN HELPM EBROT HERIA MREAC HINGO UTMYW IFELE FTMEI AMALL ALONE BRIAN DOVIS ITMEI AMALL SADAN DALON EIFEE LLIKE CRYIN GBROT HER
// CIP: TEYAK QDRLP NRLLL TEYAK QBEZR TEETY YRRLA TIARM GTZJU UFRWC RTZPG MMNWJ MLBYC NRVLL POITQ UTZPG MMNWJ EAQLL PAYZL QISPC XLVVC ORLTL S
// PLAINTEXT: HELPMEDEARBRYANHELPMEBROTHERIAMREACHINGOUTMYWIFELEFTMEIAMALLALONEBRIANDOVISITMEIAMALLSADANDALONEIFEELLIKECRYING
//CIPHERTEXT: TEYAKQDRLPNRLLLTEYAKQBEZRTEETYYRRLATIARMGTZJUUFRWCRTZPGMMNWJMLBYCNRVLLPOITQUTZPGMMNWJEAQLLPAYZLQISPCXLVVCORLTLS
//			: MANLY MANLY MANLY MANLY MANLY MANLY MANLY MANLY MANLY M
// Plaintext: HELPM EDEAR AWERT OYKFM BRYAN HELPM EBROT HMJGE FALMS Y ERIAMREACHINGOUTMYWIFELEFTMEIAMALLALONEBRIANDOVISITMEIAMALLSADANDALONEIFEELLIKECRYINGBROTHER
// Ciphertex: TEYAK QDRLP MWRCR AYXQK NRLLL TEYAK QBEZR T  
//			  TEYAK QDRLP MWRCR AYXQK NRLLL TEYAK QBEZR TMWRC RAYXQ KEETY YRRLA TIARM GTZJU UFRWC RTZPG MMNWJ MLBYC NRVLL POITQ UTZPG MMNWJ EAQLL PAYZL QISPC XLVVC ORLTL S


void vigenere_analysis(VigenereText &ciphertext) {
	
	ciphertext.quadgram_score();
	VigenereText compare {"THEEUROPEANLANGUAGESAREMEMBERSOFTHESAMEFAMILYTHEIRSEPARATEEXISTENCEISAMYTHFORSCIENCEMUSICSPORTETCEUROPEUSESTHESAMEVOCABULARYTHELANGUAGESONLYDIFFERINTHEIRGRAMMARTHEIRPRONUNCIATIONANDTHEIRMOSTCOMMONWORDSEVERYONEREALIZESWHYANEWCOMMONLANGUAGEWOULDBEDESIRABLEONECOULDREFUSETOPAYEXPENSIVETRANSLATORSTOACHIEVETHISITWOULDBENECESSARYTOHAVEUNIFORMGRAMMARPRONUNCIATIONANDMORECOMMONWORDSIFSEVERALLANGUAGESCOALESCETHEGRAMMAROFTHERESULTINGLANGUAGEISMORESIMPLEANDREGULARTHANTHATOFTHEINDIVIDUALLANGUAGESTHENEWCOMMONLANGUAGEWILLBEMORESIMPLEANDREGULARTHANTHEEXISTINGEUROPEANLANGUAGESITWILLBEASSIMPLEASOCCIDENTALINFACTITWILLBEOCCIDENTALTOANENGLISHPERSONITWILLSEEMLIKESIMPLIFIEDENGLISHASASKEPTICALCAMBRIDGEFRIENDOFMINETOLDMEWHATOCCIDENTALISTHEEUROPEANLANGUAGESAREMEMBERSOFTHESAMEFAMILYTHEIRSEPARATEEXISTENCEISAMYTHFORSCIENCEMUSICSPORTETCEUROPEUSESTHESAMEVOCABULARYTHELANGUAGESONLYDIFFERINTHEIRGRAMMARTHEIRPRONUNCIATIONANDTHEIRMOSTCOMMONWORDSEVERYONEREALIZESWHYANEWCOMMONLANGUAGEWOULDBEDESIRABLEONECOULDREFUSETOPAYEXPENSIVETRANSLATORSTOACHIEVETHISITWOULDBENECESSARYTOHAVEUNIFORMGRAMMARPRONUNCIATIONANDMORECOMMONWORDSIFSEVERALLANGUAGESCOALESCETHEGRAMMAROFTHERESULTINGLANGUAGEISMORESIMPLEANDREGULARTHANTHATOFTHEINDIVIDUALLANGUAGESTHENEWCOMMONLANGUAGEWILLBEMORESIMPLEANDREGULARTHANTHEEXISTINGEUROPEANLANGUAGESITWILLBEASSIMPLEASOCCIDENTALINFACTITWILLBEOCCIDENTALTOANENGLISHPERSONITWILLSEEMLIKESIMPLIFIEDENGLISHASASKEPTICALCAMBRIDGEFRIENDOFMINETOLDMEWHATOCCIDENTALISTHEEUROPEANLANGUAGESAREMEMBERSOFTHESAMEFAMILYTHEIRSEPARATEEXISTENCEISAMYTHFORSCIENCEMUSICSPORTETCEUROPEUSESTHESAMEVOCABULARYTHELANGUAGESONLYDIFFERINTHEIRGRAMMARTHEIRPRONUNCIATIONANDTHEIRMOSTCOMMONWORDSEVERYONEREALIZESWHYANEWCOMMONLANGUAGEWOULDBEDESIRABLEONECOULDREFUSETOPAYEXPENSIVETRANSLATORSTOACHIEVETHISITWOULDBENECESSARYTOHAVEUNIFORMGRAMMARPRONUNCIATIONANDMORECOMMONWORDSIFSEVERALLANGUAGESCOALESCETHEGRAMMAROFTHERESULTINGLANGUAGEISMORESIMPLEANDREGULARTHANTHATOFTHEINDIVIDUALLANGUAGESTHENEWCOMMONLANGUAGEWILLBEMORESIMPLEANDREGULARTHANTHEEXISTINGEUROPEANLANGUAGESITWILLBEASSIMPLEASOCCIDENTALINFACTITWILLBEOCCIDENTALTOANENGLISHPERSONITWILLSEEMLIKESIMPLIFIEDENGLISHASASKEPTICALCAMBRIDGEFRIENDOFMINETOLDMEWHATOCCIDENTALISTHEEUROPEANLANGUAGESAREMEMBERSOFTHESAMEFAMILYTHEIRSEPARATEEXISTENCEISAMYTHFORSCIENCEMUSICSPORTETCEUROPEUSESTHESAMEVOCABULARYTHELANGUAGESONLYDIFFERINTHEIRGRAMMARTHEIRPRONUNCIATIONANDTHEIRMOSTCOMMONWORDSEVERYONEREALIZESWHYANEWCOMMONLANGUAGEWOULDBEDESIRABLEONECOULDREFUSETOPAYEXPENSIVETRANSLATORSTOACHIEVETHISITWOULDBENECESSARYTOHAVEUNIFORMGRAMMARPRONUNCIATIONANDMORECOMMONWORDSIFSEVERALLANGUAGESCOALESCETHEGRAMMAROFTHERESULTINGLANGUAGEISMORESIMPLEANDREGULARTHANTHATOFTHEINDIVIDUALLANGUAGESTHENEWCOMMONLANGUAGEWILLBEMORESIMPLEANDREGULARTHANTHEEXISTINGEUROPEANLANGUAGESITWILLBEASSIMPLEASOCCIDENTALINFACTITWILLBEOCCIDENTALTOANENGLISHPERSONITWILLSEEMLIKESIMPLIFIEDENGLISHASASKEPTICALCAMBRIDGEFRIENDOFMINETOLDMEWHATOCCIDENTALISTHEEUROPEANLANGUAGESAREMEMBERSOFTHESAMEFAMILYTHEIRSEPARATEEXISTENCEISAMYTHFORSCIENCEMUSICSPORTETCEUROPEUSESTHESAMEVOCABULARYTHELANGUAGESONLYDIFFERINTHEIRGRAMMARTHEIRPRONUNCIATIONANDTHEIRMOSTCOMMONWORDSEVERYONEREALIZESWHYANEWCOMMONLANGUAGEWOULDBEDESIRABLEONECOULDREFUSETOPAYEXPENSIVETRANSLATORSTOACHIEVETHISITWOULDBENECESSARYTOHAVEUNIFORMGRAMMARPRONUNCIATIONANDMORECOMMON", ciphertext.length};
	compare.quadgram_score();
	std::cout << "Compare Score: " << compare.score << '\n';
	std::cout << "Score of the ciphertext: " << ciphertext.score << '\n' << "-----------------------------------" << '\n';
	
	size_t best_key_length {ciphertext.length};
	double highest_score {min_quadgram_score};
	for (int key_length = 2; key_length < ciphertext.length; ++key_length) {
		
		//Try not to repeat keys
		if (key_length > 2*best_key_length) break;
		
		//Guessing Keys character by character
		for (int i = 0; i < key_length; ++i) {
			ciphertext.key = decryption_key_attempt (ciphertext.encrypted,i,ciphertext.key);
			ciphertext.decrypted = decrypting (ciphertext.encrypted,ciphertext.key);
			ciphertext.quadgram_score();
			if ((highest_score < ciphertext.score) && (ciphertext.score > (compare.score - 1500))){
				ciphertext.print_status();
				highest_score = ciphertext.score;
				best_key_length = key_length;
			}
		}
		ciphertext.key = ciphertext.key + int_to_char [0];
	}
}

int main() {
	
	VigenereText ciphertext;
	std::cout << "Ciphertext: ";
	ciphertext.read_encrypted();
	vigenere_analysis(ciphertext);
	
	return 0;
}
